# Generated by Django 5.0.3 on 2024-11-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم العقار')),
                ('address', models.CharField(max_length=255, verbose_name='عنوان العقار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف العقار')),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الإيجاري')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح للإيجار')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المستأجر')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.property', verbose_name='العقار المستأجر')),
            ],
            options={
                'verbose_name': 'مستأجر',
                'verbose_name_plural': 'المستأجرون',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
            },
        ),
    ]
