# Generated by Django 5.1.2 on 2024-11-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
