# Generated by Django 5.0.2 on 2024-11-04 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'دفعة', 'verbose_name_plural': 'الدفعات'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'عقار', 'verbose_name_plural': 'العقارات'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'مستأجر', 'verbose_name_plural': 'المستأجرون'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='phone',
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rentals.tenant', verbose_name='المستأجر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف العقار'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاح للإيجار'),
        ),
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='اسم العقار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rentals.property', verbose_name='العقار المستأجر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الإيجاري'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='البريد الإلكتروني'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم المستأجر'),
        ),
    ]
