# Generated by Django 5.0.3 on 2024-11-04 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_phone_tenant_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المرفق')),
                ('description', models.TextField(blank=True, verbose_name='وصف المرفق')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='rentals.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الدفع')),
                ('method', models.CharField(choices=[('cash', 'نقدا'), ('bank', 'تحويل بنكي')], max_length=50, verbose_name='طريقة الدفع')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.lease', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'دفعات',
            },
        ),
    ]
