# Generated by Django 5.0.3 on 2024-11-05 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_amenity_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المالك')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(max_length=200, verbose_name='عنوان المالك')),
            ],
            options={
                'verbose_name': 'مالك',
                'verbose_name_plural': 'المالكون',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='وصف الصيانة')),
                ('date', models.DateField(verbose_name='تاريخ الصيانة')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الصيانة')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تم الإنجاز')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='rentals.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'سجل الصيانة',
                'verbose_name_plural': 'سجلات الصيانة',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوى الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='rentals.property', verbose_name='العقار')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'ملاحظة',
                'verbose_name_plural': 'الملاحظات',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.owner', verbose_name='المالك'),
        ),
    ]
