# Generated by Django 5.1.2 on 2024-11-06 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_document_invoice_paymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم جهة الاتصال')),
                ('relationship', models.CharField(max_length=50, verbose_name='العلاقة')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='rentals.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'جهة اتصال',
                'verbose_name_plural': 'جهات الاتصال',
            },
        ),
    ]
