# Generated by Django 5.0.3 on 2024-11-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.TextField(blank=True, verbose_name='عنوان المالك'),
        ),
    ]
