# Generated by Django 5.0.3 on 2024-11-07 12:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_owner_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='وصف التصنيف')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التأخير'),
        ),
        migrations.AddField(
            model_name='lease',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='التأمين'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم المستأجر'),
        ),
        migrations.AddField(
            model_name='property',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='properties', to='rentals.tag', verbose_name='التصنيفات'),
        ),
        migrations.CreateModel(
            name='TenantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(max_length=100, verbose_name='اسم المراجع')),
                ('review_date', models.DateField(verbose_name='تاريخ المراجعة')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rentals.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'مراجعة المستأجر',
                'verbose_name_plural': 'المراجعات المستأجرين',
            },
        ),
    ]
